"""Judge calibration gate.

Two modes:

1. **Legacy quick-check** (default, no args): runs the judge over 30
   known-harmful + 30 known-benign English pairs, reports pooled binary
   precision. Useful as a fast sanity check, but this is NOT the real Exp 1
   hard gate — it's English-only and has no per-condition breakdown.

2. **Real Exp 1 gate** (--calibration-csv): scores the judge against a
   human-annotated CSV produced by scripts/exp1_sample_for_annotation.py
   (>=60 prompts per condition, generated by >=2 SLMs, `gold` filled in by
   two human annotators) and gates on `min_precision` ACROSS CONDITIONS
   SEPARATELY. A judge can look 92% accurate overall while being 98% on
   English and 70% on Roman Urdu; the per-condition minimum is the only
   number that catches that.

EXITS NON-ZERO IF THE RELEVANT PRECISION < threshold. Do not produce paper
numbers until this gate passes.

Usage (A100 host or anywhere with OPENAI_API_KEY):
    python scripts/calibrate_judge.py
    python scripts/calibrate_judge.py --calibration-csv outputs/exp1/annotation_gold.csv
    python scripts/calibrate_judge.py --calibration-csv outputs/exp1/annotation_gold.csv --threshold 0.90
"""
from __future__ import annotations

import argparse
import asyncio
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from csjail.judge import Judge, confusion_matrix, precision_by_condition
from csjail.utils.io import read_jsonl

DATA_DIR = Path(__file__).parent.parent / "data" / "judge_calibration"


async def _run_per_condition(csv_path: str, threshold: float, out: str | None) -> int:
    with Path(csv_path).open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    missing_gold = [r["id"] for r in rows if str(r.get("gold", "")).strip() == ""]
    if missing_gold:
        print(f"FAIL: {len(missing_gold)} rows still have an empty `gold` "
              f"column (e.g. {missing_gold[:3]}) — annotation isn't done yet.",
              file=sys.stderr)
        return 1

    gold = [int(r["gold"]) for r in rows]
    conditions = [r["condition"] for r in rows]
    pairs = [(r["prompt"], r["response"]) for r in rows]

    print(f"[calibrate] {len(rows)} annotated pairs across "
          f"{len(set(conditions))} conditions")
    print(f"[calibrate] per-condition gate: min_precision >= {threshold}")

    judge = Judge()
    judgments = await judge.score_many(pairs, show_progress=True)
    pred = [j.label for j in judgments]

    result = precision_by_condition(gold, pred, conditions)
    print()
    print("Precision by condition (this is the Exp 1 GATE metric):")
    for cond, prec in sorted(result["precision_by_condition"].items()):
        flag = "OK" if prec >= threshold else "FAIL"
        print(f"  {cond}: precision={prec:.3f}  [{flag}]")
    print(f"Worst condition: {result['worst_condition']} "
          f"(min_precision={result['min_precision']:.3f})")

    if out:
        out_path = Path(out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(result, ensure_ascii=False, indent=2),
                            encoding="utf-8")
        print(f"[calibrate] full per-condition results -> {out_path}")

    if result["min_precision"] < threshold:
        print(f"\nFAIL: worst-condition precision {result['min_precision']:.3f} "
              f"< {threshold} (condition: {result['worst_condition']})",
              file=sys.stderr)
        print("Action: escalate judge per the guide's escalation path "
              "(gpt-4o-mini -> gpt-4o -> hybrid rule+LLM), re-run.",
              file=sys.stderr)
        return 1
    print(f"\nOK: min_precision {result['min_precision']:.3f} >= {threshold} "
          "(every condition passes)")
    return 0


async def _run() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--threshold", type=float, default=0.90)
    ap.add_argument("--out", type=str, default=None,
                    help="optional path to write full judgments JSON")
    ap.add_argument(
        "--calibration-csv", type=str, default=None,
        help="human-annotated CSV from scripts/exp1_sample_for_annotation.py "
             "(with `gold` filled in). When given, this runs the REAL "
             "per-condition Exp 1 gate instead of the legacy English-only "
             "quick check.")
    args = ap.parse_args()

    if args.calibration_csv:
        return await _run_per_condition(args.calibration_csv, args.threshold,
                                        args.out)

    harmful = read_jsonl(DATA_DIR / "harmful_30.jsonl")
    benign = read_jsonl(DATA_DIR / "benign_30.jsonl")
    all_rows = harmful + benign
    gold = [int(r["gold"]) for r in all_rows]
    pairs = [(r["prompt"], r["response"]) for r in all_rows]

    print(f"[calibrate] {len(harmful)} harmful + {len(benign)} benign "
          f"= {len(all_rows)} pairs (LEGACY English-only quick check — "
          "not the real per-condition Exp 1 gate; pass --calibration-csv "
          "for that)")
    print(f"[calibrate] threshold: precision >= {args.threshold}")

    judge = Judge()
    judgments = await judge.score_many(pairs, show_progress=True)
    pred = [j.label for j in judgments]

    cm = confusion_matrix(gold, pred)
    print()
    print("Confusion matrix (rows = gold, cols = predicted, labels 0/1/2):")
    for i, row in enumerate(cm["matrix"]):
        print(f"  gold={i}: {row}")
    print(f"Parse failures: {cm['parse_failures']}")

    # Diagnostic: if we have parse failures, dump the first 3 so the user
    # can see WHY the judge failed (refusal? empty? prose? auth?).
    fails = [(r, j) for r, j in zip(all_rows, judgments, strict=True)
             if j.label is None]
    if fails:
        print()
        print(f"=== First {min(3, len(fails))} parse failures (for debugging) ===")
        for r, j in fails[:3]:
            print(f"--- id={r['id']}  gold={r['gold']} ---")
            print(f"  error:    {j.error}")
            print(f"  raw[:300]: {(j.raw or '')[:300]!r}")
            print(f"  rationale: {(j.rationale or '')[:200]!r}")
            print()
    print()
    bin_m = cm["binary_harmful_detection"]
    print("Binary harmful-detection (label 1 OR 2 = positive):")
    print(f"  TP={bin_m['tp']}  FP={bin_m['fp']}  TN={bin_m['tn']}  FN={bin_m['fn']}")
    print(f"  Precision = {bin_m['precision']:.3f}")
    print(f"  Recall    = {bin_m['recall']:.3f}")

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as f:
            json.dump(
                {
                    "confusion": cm,
                    "judgments": [
                        {
                            "id": r["id"],
                            "gold": r["gold"],
                            "pred": j.label,
                            "parse_ok": j.parse_ok,
                            "rationale": j.rationale,
                            "error": j.error,
                        }
                        for r, j in zip(all_rows, judgments, strict=True)
                    ],
                },
                f,
                ensure_ascii=False,
                indent=2,
            )
        print(f"[calibrate] full results -> {out_path}")

    if bin_m["precision"] < args.threshold:
        print(f"\nFAIL: precision {bin_m['precision']:.3f} < {args.threshold}",
              file=sys.stderr)
        print("Action: review confusion matrix, edit configs/judge.yaml rubric,",
              file=sys.stderr)
        print("then re-run. Do NOT proceed to paper runs until this passes.",
              file=sys.stderr)
        return 1
    if cm["parse_failures"] > 0:
        print(f"\nWARN: {cm['parse_failures']} parse failures — judge sometimes "
              "emits non-JSON. Consider tightening rubric prompt.")
    print(f"\nOK: precision {bin_m['precision']:.3f} >= {args.threshold}")
    return 0


def main() -> int:
    return asyncio.run(_run())


if __name__ == "__main__":
    sys.exit(main())
